{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "shifts.serviceAccountName" . }}
  labels:
{{ include "shifts.labels" . | indent 4 }}
{{- end -}}
