apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: users-hpa
spec:
 maxReplicas: 5
 minReplicas: 1
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: users-deployment
 targetCPUUtilizationPercentage: 70
